#ifndef RETURNCODE_HPP
# define RETURNCODE_HPP

// LIST OF ERRORS


// CONNECTION REGISTRATION

	// REPLY
	#define	RPL_WELCOME	001
	// #define RPL_YOURESERVICE 	TO DO?

	// PASS
	#define ERR_NEEDMOREPARAMS
	#define ERR_ALREADYREGISTRED

	// NICK

	#define ERR_NONICKNAMEGIVEN 401
	#define	ERR_NICKNAMEINUSE 433
	#define ERR_UNAVAILRESOURCE 437
	#define ERR_ERRONEUSNICKNAME 432
	#define ERR_NICKCOLLISION 436
	#define ERR_RESTRICTED 484

// CHANNEL CONNECTION

	#define ERR_NEEDMOREPARAMS 461
	#define ERR_INVITEONLYCHAN 473
	#define ERR_CHANNELISFULL 471
	#define ERR_NOSUCHCHANNEL 403
	#define ERR_TOOMANYTARGETS 407
	#define ERR_BANNEDFROMCHAN 474
	#define ERR_BADCHANNELKEY 475
	#define ERR_BADCHANMASK 476
	#define ERR_TOOMANYCHANNELS 405
	#define ERR_NONICKNAMEGIVEN 
	#define	ERR_NICKNAMEINUSE
	#define ERR_UNAVAILRESOURCE
	#define ERR_ERRONEUSNICKNAME
	#define ERR_NICKCOLLISION
	#define ERR_RESTRICTED

	// USER
	#define  ERR_ALREADYREGISTRED


	// OPER
	#define ERR_NEEDMOREPARAMS
	#define RPL_YOUREOPER
	#define ERR_NOOPERHOST
	#define ERR_PASSWDMISMATCH

	// USER MODE
	#define ERR_NEEDMOREPARAMS
	#define ERR_USERSDONTMATCH
	#define ERR_UMODEUNKNOWNFLAG
	#define RPL_UMODEIS


#endif