#ifndef RETURNCODE_HPP
# define RETURNCODE_HPP

// LIST OF ERRORS


// CONNECTION REGISTRATION

	// REPLY
	#define	RPL_WELCOME	001

	// PASS

	// NICK ERRORS

	#define ERR_NONICKNAMEGIVEN 401
	#define	ERR_NICKNAMEINUSE 433
	#define ERR_UNAVAILRESOURCE 437
	#define ERR_ERRONEUSNICKNAME 432
	#define ERR_NICKCOLLISION 436
	#define ERR_RESTRICTED 484

// CHANNEL CONNECTION

	#define ERR_NEEDMOREPARAMS 461
	#define ERR_INVITEONLYCHAN 473
	#define ERR_CHANNELISFULL 471
	#define ERR_NOSUCHCHANNEL 403
	#define ERR_TOOMANYTARGETS 407
	#define ERR_BANNEDFROMCHAN 474
	#define ERR_BADCHANNELKEY 475
	#define ERR_BADCHANMASK 476
	#define ERR_TOOMANYCHANNELS 405

#endif